name: Apply Patch from Issue Comment

on:
  issue_comment:
    types: [created]

jobs:
  apply-patch:
    if: startsWith(github.event.comment.body, '/apply-patch')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Extract patch
        run: |
          echo "${{ github.event.comment.body }}" | sed -n '/```patch/,/```/p' | sed '1d;$d' > patch.diff
          cat patch.diff

      - name: Apply patch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b chatgpt-patch-${{ github.run_id }}
          git apply --whitespace=fix patch.diff
          git add -A
          git commit -m "Apply patch from issue #${{ github.event.issue.number }}"

      - name: Push branch
        run: git push origin chatgpt-patch-${{ github.run_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: chatgpt-patch-${{ github.run_id }}
          title: "ChatGPT Patch from issue #${{ github.event.issue.number }}"
          body: "This PR was created automatically from a /apply-patch comment."
          base: master
